blank_pull_requests_enabled: false
contact_links:
  - name: LightSpeed WP Support
    url: https://lightspeedwp.agency
    about: For paid support inquiries, please contact us directly via our website.
  - name: WordPress Block Theme Documentation
    url: https://developer.wordpress.org/themes/block-themes/
    about: Official WordPress documentation for block theme development
  - name: Full Site Editing Guide
    url: https://wordpress.org/documentation/article/site-editor/
    about: Learn about WordPress Full Site Editing features
  - name: Theme.json Reference
    url: https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/
    about: Complete reference for theme.json configuration
